pipeline {
    agent any
    
    stages {
        stage('Clonage du référentiel') {
            steps {
                git 'https://github.com/TouatiM199/mon_proj.git'
            }
        }
        
        stage('Build') {
            steps {
                // Ajoutez les étapes de build ici
            }
        }
        
        stage('Tests') {
            steps {
                // Ajoutez les étapes de tests ici
            }
        }
        
        stage('Déploiement') {
            steps {
                // Ajoutez les étapes de déploiement ici
            }
        }
    }
}

