# Generated by Django 4.1.7 on 2023-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
