# Generated by Django 4.1.7 on 2023-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0002_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
