# Generated by Django 4.1.7 on 2023-03-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0003_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='image',
        ),
        migrations.AddField(
            model_name='signature',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
