# Generated by Django 4.1.7 on 2023-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0004_remove_signature_image_signature_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='signature',
        ),
        migrations.AddField(
            model_name='signature',
            name='image',
            field=models.ImageField(default='default_signature.jpg', upload_to='signatures'),
        ),
        migrations.AddField(
            model_name='signature',
            name='image_type',
            field=models.CharField(default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
