# Generated by Django 4.1.7 on 2023-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0006_instructeur_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='')),
            ],
        ),
    ]
